//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swtor.Dps.DamageModel.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swtor.Dps.DamageModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Configuration&quot;: {
        ///		&quot;Level&quot;: 65,
        ///		&quot;StandardDamage&quot;: 4465,
        ///		&quot;StandardHealth&quot;: 27510,
        ///		&quot;DualWield&quot; : 1,
        ///
        ///		&quot;MainHand&quot;: {
        ///			&quot;DamageMin&quot;: 794,
        ///			&quot;DamageMax&quot;: 1191,
        ///			&quot;Power&quot;: 1589
        ///		},
        ///
        ///		&quot;OffHand&quot;: {
        ///			&quot;DamageMin&quot;: 794,
        ///			&quot;DamageMax&quot;: 1191,
        ///			&quot;Power&quot;: 1589,
        ///			&quot;Multiplier&quot;: 0.55
        ///		},
        ///
        ///		&quot;BaseMasteryPoints&quot;: 4769,
        ///		&quot;AugmentMasteryPoints&quot;: 0,
        ///
        ///		&quot;AccuracyPoints&quot;: 685,
        ///		&quot;AlacrityPoints&quot;: 736,
        ///		&quot;CriticalPoints&quot;: 1161,
        ///		&quot;PowerPoints&quot;: 2539,
        ///
        ///		&quot;BaseAlacrity&quot;: 0.03,
        ///		&quot;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
    }
}
