//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swtor.Dps.DamageModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swtor.Dps.DamageModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Configuration&quot;: {
        ///    &quot;Level&quot;: 70,
        ///    &quot;DualWield&quot;: true,
        ///    &quot;MainHand&quot;: {
        ///      &quot;DamageMin&quot;: 1270,
        ///      &quot;DamageMax&quot;: 1904,
        ///      &quot;Power&quot;: 2540,
        ///      &quot;Multiplier&quot;: 1.0,
        ///      &quot;DamageType&quot;: 2
        ///    },
        ///    &quot;OffHand&quot;: {
        ///      &quot;DamageMin&quot;: 1169,
        ///      &quot;DamageMax&quot;: 1754,
        ///      &quot;Power&quot;: 2339,
        ///      &quot;Multiplier&quot;: 0.55,
        ///      &quot;DamageType&quot;: 2
        ///    },
        ///    &quot;StandardDamage&quot;: 7520,
        ///    &quot;StandardHealth&quot;: 40495,
        ///    &quot;BaseMasteryPoints&quot;: 6372,
        ///    &quot;BasePowerPoints&quot;: 4321,
        ///    &quot;ExtraMasteryPoints&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
    }
}
